// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.sc.seis.sod.model.common;

//
// IDL:iris.edu/Fissures/Error:1.0
//
/***/

final public class Error 
{
    public
    Error()
    {
    }

    public
    Error(int error_code,
          String error_description)
    {
        super(error_description);
        this.error_code = error_code;
        this.error_description = error_description;
    }

    public int error_code;
    public String error_description;
}
