// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.sc.seis.sod.model.common;

//
// IDL:iris.edu/Fissures/Orientation:1.0
//
/** represents the orientation of a single component of a seismometer.
 **/

final public class Orientation {
    
    public
    Orientation()
    {
    }

    public
    Orientation(float azimuth,
                float dip)
    {
        this.azimuth = azimuth;
        this.dip = dip;
    }

    public float azimuth;
    public float dip;
}
