// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package edu.sc.seis.sod.model.common;

import java.io.Serializable;

//
// IDL:iris.edu/Fissures/PointDistanceArea:1.0
//
/***/

public class PointDistanceAreaImpl extends Area
{

    public PointDistanceAreaImpl(float latitude,
                 float longitude,
                 QuantityImpl min_distance,
                 QuantityImpl max_distance) {
    this.latitude = latitude;
    this.longitude = longitude;
    this.min_distance = min_distance;
    this.max_distance = max_distance;
    }

    protected PointDistanceAreaImpl() {

    }

    public static Serializable createEmpty() {
        return new PointDistanceAreaImpl();
    }

    public String toString() {
        return "PointDistance ("+latitude+","+longitude+") from "+min_distance+" to "+max_distance;
    }
    
    public float latitude;

    //
    // IDL:iris.edu/Fissures/PointDistanceArea/longitude:1.0
    //
    /***/

    public float longitude;

    //
    // IDL:iris.edu/Fissures/PointDistanceArea/min_distance:1.0
    //
    /** must be either angular or length */

    public QuantityImpl min_distance;

    //
    // IDL:iris.edu/Fissures/PointDistanceArea/max_distance:1.0
    //
    /** must be either angular or length */

    public QuantityImpl max_distance;


}
