// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.sc.seis.sod.model.seismogram;

//
// IDL:iris.edu/Fissures/IfTimeSeries/EncodedData:1.0
//
/***/

final public class EncodedData implements org.omg.CORBA.portable.IDLEntity
{
    public
    EncodedData()
    {
    }

    public
    EncodedData(short compression,
                byte[] values,
                int num_points,
                boolean byte_order)
    {
        this.compression = compression;
        this.values = values;
        this.num_points = num_points;
        this.byte_order = byte_order;
    }

    public short compression;
    public byte[] values;
    public int num_points;
    public boolean byte_order;
}
