// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.sc.seis.sod.model.seismogram;

import edu.sc.seis.sod.model.common.Time;
import edu.sc.seis.sod.model.station.ChannelId;

//
// IDL:iris.edu/Fissures/IfSeismogramDC/RequestFilter:1.0
//
/***/

final public class RequestFilter implements org.omg.CORBA.portable.IDLEntity
{
    public
    RequestFilter()
    {
    }

    public
    RequestFilter(ChannelId channel_id,
                  Time start_time,
                  Time end_time)
    {
        this.channel_id = channel_id;
        this.start_time = start_time;
        this.end_time = end_time;
    }

    public ChannelId channel_id;
    public Time start_time;
    public Time end_time;
}
