// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.sc.seis.sod.model.seismogram;

import edu.sc.seis.seisFile.ChannelTimeWindow;
import edu.sc.seis.seisFile.fdsnws.stationxml.Channel;
import edu.sc.seis.sod.model.common.MicroSecondDate;
import edu.sc.seis.sod.model.station.ChannelId;

//
// IDL:iris.edu/Fissures/IfSeismogramDC/RequestFilter:1.0
//
/***/

final public class RequestFilter implements org.omg.CORBA.portable.IDLEntity
{
    
    RequestFilter()
    {
    }
    
    public static RequestFilter of(LocalSeismogramImpl seismogram) {
        return new RequestFilter(seismogram.getChannelID(),
                          new MicroSecondDate(seismogram.begin_time),
                          new MicroSecondDate(seismogram.getEndTime()));
    }


    public
    RequestFilter(Channel channel,
                  MicroSecondDate start_time,
                  MicroSecondDate end_time)
    {
        this.channel_id = new ChannelId(channel);
        this.start_time = start_time;
        this.end_time = end_time;
    }

    public
    RequestFilter(ChannelId channel_id,
                  MicroSecondDate start_time,
                  MicroSecondDate end_time)
    {
        this.channel_id = channel_id;
        this.start_time = start_time;
        this.end_time = end_time;
    }
    
    public ChannelTimeWindow asChannelTimeWindow() {
        return new ChannelTimeWindow(channel_id.getNetworkId().getCode(),
                                     channel_id.getStationCode(),
                                     channel_id.getLocCode(),
                                     channel_id.getChannelCode(),
                                     start_time,
                                     end_time);
    }

    public ChannelId channel_id;
    public MicroSecondDate start_time;
    public MicroSecondDate end_time;
}
