// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.sc.seis.sod.model.seismogram;

//
// IDL:iris.edu/Fissures/IfTimeSeries/SequenceOutOfOrder:1.0
//
/***/

final public class SequenceOutOfOrder extends org.omg.CORBA.UserException
{

    public
    SequenceOutOfOrder(int last_valid_seq_num)
    {
        this.last_valid_seq_num = last_valid_seq_num;
    }

    public
    SequenceOutOfOrder(String reason,
                       int last_valid_seq_num)
    {
        super(reason);
        this.last_valid_seq_num = last_valid_seq_num;
    }

    public int last_valid_seq_num;
}
