// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.sc.seis.sod.model.station;

import edu.sc.seis.sod.model.common.MicroSecondDate;
import edu.sc.seis.sod.model.common.Time;

//
// IDL:iris.edu/Fissures/IfNetwork/ChannelId:1.0
//
/** Identifies a Channel. The additional begin_time is needed 
 *  as channel
 *  codes are frequently reused if, for example a new sensor is install
 *  in place of the old one, which properly creates a new Channel.
 *  The begin_time should be equal to the begining
 *  effective time of the channel, which is also in the Channel object. 
 **/

final public class ChannelId 
{
    public
    ChannelId()
    {
    }

    public
    ChannelId(NetworkId network_id,
              String station_code,
              String site_code,
              String channel_code,
              MicroSecondDate begin_time)
    {
        this.network_id = network_id;
        this.station_code = station_code;
        this.site_code = site_code;
        this.channel_code = channel_code;
        this.begin_time = begin_time;
    }

    public NetworkId network_id;
    public String station_code;
    public String site_code;
    public String channel_code;
    public MicroSecondDate begin_time;
}
