// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package edu.sc.seis.sod.model.station;


//
// IDL:iris.edu/Fissures/IfNetwork/Clock:1.0
//
/***/

public class ClockImpl extends SeismicHardwareImpl {
    
    public String type;
    
	protected ClockImpl() {
    }

    public static ClockImpl createEmpty() {
	return new ClockImpl();
    }

    public ClockImpl(int id_number,
                      String manufacturer,
                      String serial_number,
                      String model,
                      String type) {
        this.id_number = id_number;
        this.manufacturer = manufacturer;
        this.serial_number = serial_number;
        this.model = model;
        this.type = type;
    }

}
