// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.sc.seis.sod.model.station;

//
// IDL:iris.edu/Fissures/IfNetwork/CoefficientErrored:1.0
//
/***/

final public class CoefficientErrored implements org.omg.CORBA.portable.IDLEntity
{
    public
    CoefficientErrored()
    {
    }

    public
    CoefficientErrored(float value,
                       float error)
    {
        this.value = value;
        this.error = error;
    }

    public float value;
    public float error;
}
