// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.sc.seis.sod.model.station;

//
// IDL:iris.edu/Fissures/IfNetwork/ComplexNumberErrored:1.0
//
/***/

final public class ComplexNumberErrored  {
    public
    ComplexNumberErrored()
    {
    }

    public
    ComplexNumberErrored(float real,
                         float real_error,
                         float imaginary,
                         float imaginary_error)
    {
        this.real = real;
        this.real_error = real_error;
        this.imaginary = imaginary;
        this.imaginary_error = imaginary_error;
    }

    public float real;
    public float real_error;
    public float imaginary;
    public float imaginary_error;
}
