// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.sc.seis.sod.model.station;

import edu.sc.seis.sod.model.common.QuantityImpl;
import edu.sc.seis.sod.model.common.SamplingImpl;

//
// IDL:iris.edu/Fissures/IfNetwork/Decimation:1.0
//
/** A decimation step within a response stage. This is equivalent to 
 *  blockette 57 within the SEED manual. */

final public class Decimation implements org.omg.CORBA.portable.IDLEntity
{
    public
    Decimation()
    {
    }

    public
    Decimation(SamplingImpl input_rate,
               int factor,
               int offset,
               QuantityImpl estimated_delay,
               QuantityImpl correction_applied)
    {
        this.input_rate = input_rate;
        this.factor = factor;
        this.offset = offset;
        this.estimated_delay = estimated_delay;
        this.correction_applied = correction_applied;
    }

    public SamplingImpl input_rate;
    public int factor;
    public int offset;
    public QuantityImpl estimated_delay;
    public QuantityImpl correction_applied;
}
