// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.sc.seis.sod.model.station;

//
// IDL:iris.edu/Fissures/IfNetwork/DuplicateSiteId:1.0
//
/***/

final public class DuplicateSiteId extends Exception
{

    public
    DuplicateSiteId(SiteId site)
    {
        this.site = site;
    }

    public
    DuplicateSiteId(String reason,
                    SiteId site)
    {
        super(reason);
        this.site = site;
    }

    public SiteId site;
}
