// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.sc.seis.sod.model.station;

//
// IDL:iris.edu/Fissures/IfNetwork/DuplicateChannelId:1.0
//
/***/

final public class DuplicateChannelId extends Exception
{

    public
    DuplicateChannelId(ChannelId channel)
    {
        this.channel = channel;
    }

    public
    DuplicateChannelId(String reason,
                       ChannelId channel)
    {
        super(reason);
        this.channel = channel;
    }

    public ChannelId channel;
}
