// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.sc.seis.sod.model.station;

//
// IDL:iris.edu/Fissures/IfNetwork/FilterType:1.0
//
/** The type of response filter, these correspond to blockette 54 for
 *coefficient, 53 for polezero and 55 for list. List is for compatibility
 *with very old stations, and should not be used if possible. */

final public class FilterType 
{
    private static FilterType [] values_ = new FilterType[3];
    private int value_;

    public final static int _COEFFICIENT = 0;
    public final static FilterType COEFFICIENT = new FilterType(_COEFFICIENT);
    public final static int _POLEZERO = 1;
    public final static FilterType POLEZERO = new FilterType(_POLEZERO);
    public final static int _LIST = 2;
    public final static FilterType LIST = new FilterType(_LIST);

    protected
    FilterType(int value)
    {
        values_[value] = this;
        value_ = value;
    }

    public int
    value()
    {
        return value_;
    }

    public static FilterType
    from_int(int value)
    {
        return values_[value];
    }
}
