// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.sc.seis.sod.model.station;

//
// IDL:iris.edu/Fissures/IfNetwork/Filter:1.0
//
/***/

final public class Filter 
{
    java.lang.Object _ob_v_;
    boolean _ob_i_;
    int _ob_d_;

    static boolean
    _OB_check(int d0, int d1)
    {
        return d0 == d1;
    }

    public
    Filter()
    {
        _ob_i_ = false;
    }

    public FilterType
    discriminator()
    {
        if(!_ob_i_)
            throw new org.omg.CORBA.BAD_OPERATION();

        return FilterType.from_int(_ob_d_);
    }

    public CoefficientFilter
    coeff_filter()
    {
        if(!_ob_i_)
            throw new org.omg.CORBA.BAD_OPERATION();

        if(!_OB_check(_ob_d_, FilterType._COEFFICIENT))
            throw new org.omg.CORBA.BAD_OPERATION();

        return (CoefficientFilter)_ob_v_;
    }

    public void
    coeff_filter(CoefficientFilter val)
    {
        _ob_i_ = true;
        _ob_d_ = FilterType._COEFFICIENT;
        _ob_v_ = val;
    }

    public PoleZeroFilter
    pole_zero_filter()
    {
        if(!_ob_i_)
            throw new org.omg.CORBA.BAD_OPERATION();

        if(!_OB_check(_ob_d_, FilterType._POLEZERO))
            throw new org.omg.CORBA.BAD_OPERATION();

        return (PoleZeroFilter)_ob_v_;
    }

    public void
    pole_zero_filter(PoleZeroFilter val)
    {
        _ob_i_ = true;
        _ob_d_ = FilterType._POLEZERO;
        _ob_v_ = val;
    }

    public ListFilter
    list_filter()
    {
        if(!_ob_i_)
            throw new org.omg.CORBA.BAD_OPERATION();

        if(!_OB_check(_ob_d_, FilterType._LIST))
            throw new org.omg.CORBA.BAD_OPERATION();

        return (ListFilter)_ob_v_;
    }

    public void
    list_filter(ListFilter val)
    {
        _ob_i_ = true;
        _ob_d_ = FilterType._LIST;
        _ob_v_ = val;
    }
}
