// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.sc.seis.sod.model.station;

//
// IDL:iris.edu/Fissures/IfNetwork/Gain:1.0
//
/** A gain applied at a response stage. This is equivalent to fields 4
 *and 5 of blockette 58 when the stage is not zero. */

final public class Gain implements org.omg.CORBA.portable.IDLEntity
{
    public
    Gain()
    {
    }

    public
    Gain(float gain_factor,
         float frequency)
    {
        this.gain_factor = gain_factor;
        this.frequency = frequency;
    }

    public float gain_factor;
    public float frequency;
}
