// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package edu.sc.seis.sod.model.station;

import edu.sc.seis.sod.model.common.MicroSecondTimeRange;

//
// IDL:iris.edu/Fissures/IfNetwork/Instrumentation:1.0
//
/***/

public class InstrumentationImpl {
    

    //
    // IDL:iris.edu/Fissures/IfNetwork/Instrumentation/the_response:1.0
    //
    /***/

    public Response the_response;

    //
    // IDL:iris.edu/Fissures/IfNetwork/Instrumentation/effective_time:1.0
    //
    /***/

    public MicroSecondTimeRange effective_time;

    //
    // IDL:iris.edu/Fissures/IfNetwork/Instrumentation/the_clock:1.0
    //
    /***/

    public ClockImpl the_clock;

    //
    // IDL:iris.edu/Fissures/IfNetwork/Instrumentation/the_sensor:1.0
    //
    /***/

    public SensorImpl the_sensor;

    //
    // IDL:iris.edu/Fissures/IfNetwork/Instrumentation/das:1.0
    //
    /***/

    public DataAcqSysImpl das;
    
	protected InstrumentationImpl() {
    }

    public static InstrumentationImpl createEmpty() {
	return new InstrumentationImpl();
    }

    public InstrumentationImpl(Response the_response,
                               MicroSecondTimeRange effective_time,
                               ClockImpl the_clock,
                               SensorImpl the_sensor,
                               DataAcqSysImpl das) {
        this.the_response = the_response;
        this.effective_time = effective_time;
        this.the_clock = the_clock;
        this.the_sensor =  the_sensor;
        this.das = das;
    }

}
