// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.sc.seis.sod.model.station;

import edu.sc.seis.sod.model.common.UnitImpl;

//
// IDL:iris.edu/Fissures/IfNetwork/ListFilter:1.0
//
/** Represents a list style response. Similar to blockette 55 in SEED.
 *NOTE that this style response should only be used for older data where
 *coefficients or poles and zeros are not availible. */

final public class ListFilter  {
    public
    ListFilter()
    {
    }

    public
    ListFilter(float[] frequency,
               UnitImpl frequency_unit,
               float[] amplitude,
               float[] amplitude_error,
               float[] phase,
               UnitImpl phase_unit,
               float[] phase_error)
    {
        this.frequency = frequency;
        this.frequency_unit = frequency_unit;
        this.amplitude = amplitude;
        this.amplitude_error = amplitude_error;
        this.phase = phase;
        this.phase_unit = phase_unit;
        this.phase_error = phase_error;
    }

    public float[] frequency;
    public UnitImpl frequency_unit;
    public float[] amplitude;
    public float[] amplitude_error;
    public float[] phase;
    public UnitImpl phase_unit;
    public float[] phase_error;
}
