// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.sc.seis.sod.model.station;

import edu.sc.seis.sod.model.common.Time;

//
// IDL:iris.edu/Fissures/IfNetwork/NetworkId:1.0
//
/** Identifies a network. The additional begin_time is needed for temporary
 *  PASSCAL networks. The begin_time should be equal to the beginin 
 *  effective time of the network, which is also in the NetworkAttributes. 
 **/

final public class NetworkId implements org.omg.CORBA.portable.IDLEntity
{
    public
    NetworkId()
    {
    }

    public
    NetworkId(String network_code,
              Time begin_time)
    {
        this.network_code = network_code;
        this.begin_time = begin_time;
    }

    public String network_code;
    public Time begin_time;
}
