// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.sc.seis.sod.model.station;

//
// IDL:iris.edu/Fissures/IfNetwork/Normalization:1.0
//
/** A norminalization factor, such that the stage evaluated at the
 *  frequency is 1. The constant is factored out onto this object.
 **/

final public class Normalization {
    
    public
    Normalization()
    {
    }

    public
    Normalization(float ao_normalization_factor,
                  float normalization_freq)
    {
        this.ao_normalization_factor = ao_normalization_factor;
        this.normalization_freq = normalization_freq;
    }

    public float ao_normalization_factor;
    public float normalization_freq;
}
