// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package edu.sc.seis.sod.model.station;


//
// IDL:iris.edu/Fissures/IfNetwork/SeismicHardware:1.0
//
/***/

public class SeismicHardwareImpl {
    /***/

    public int id_number;

    //
    // IDL:iris.edu/Fissures/IfNetwork/SeismicHardware/manufacturer:1.0
    //
    /***/

    public String manufacturer;

    //
    // IDL:iris.edu/Fissures/IfNetwork/SeismicHardware/serial_number:1.0
    //
    /***/

    public String serial_number;

    //
    // IDL:iris.edu/Fissures/IfNetwork/SeismicHardware/model:1.0
    //
    /***/

    public String model;
    
	protected SeismicHardwareImpl() {
    }

    public static SeismicHardwareImpl createEmpty() {
	return new SeismicHardwareImpl();
    }

}
