// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.3

package edu.sc.seis.sod.model.station;

//
// IDL:iris.edu/Fissures/IfNetwork/Sensor:1.0
//
/***/

public class SensorImpl extends SeismicHardwareImpl
{
    /***/

    public float nominal_high_freq;

    //
    // IDL:iris.edu/Fissures/IfNetwork/Sensor/nominal_low_freq:1.0
    //
    /***/

    public float nominal_low_freq;
    
	protected SensorImpl() {
    }

    public static SensorImpl createEmpty() {
	return new SensorImpl();
    }

    public  SensorImpl(int id_number,
                       String manufacturer,
                       String serial_number,
                       String model,
                       float nominal_high_freq,
                       float nominal_low_freq) {
        this.id_number = id_number;
        this.manufacturer = manufacturer;
        this.serial_number = serial_number;
        this.model = model;
        this.nominal_high_freq = nominal_high_freq;
        this.nominal_low_freq = nominal_low_freq;
    }

}
