// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.sc.seis.sod.model.station;

//
// IDL:iris.edu/Fissures/IfNetwork/Sensitivity:1.0
//
/** The overall sensitivity of the response. This is equivalent to fields 4
 *and 5 of blockette 58 when the stage is zero. */

final public class Sensitivity 
{
    public
    Sensitivity()
    {
    }

    public
    Sensitivity(float sensitivity_factor,
                float frequency)
    {
        this.sensitivity_factor = sensitivity_factor;
        this.frequency = frequency;
    }

    public float sensitivity_factor;
    public float frequency;
}
