// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.sc.seis.sod.model.station;

import edu.sc.seis.sod.model.common.Time;

//
// IDL:iris.edu/Fissures/IfNetwork/SiteId:1.0
//
/** Identifies a Site. Sites in the FISSURES model are roughly equivalent 
 *  to location identifiers in SEED. The additional begin_time is needed 
 *  as site
 *  codes can be reused if, for example the site moves only a short 
 *  distance, or in the case of a new station that shares the same station
 *   code. The begin_time should be equal to the begining
 *  effective time of the site, which is also in the Site object. 
 **/

final public class SiteId implements org.omg.CORBA.portable.IDLEntity
{
    public
    SiteId()
    {
    }

    public
    SiteId(NetworkId network_id,
           String station_code,
           String site_code,
           Time begin_time)
    {
        this.network_id = network_id;
        this.station_code = station_code;
        this.site_code = site_code;
        this.begin_time = begin_time;
    }

    public NetworkId network_id;
    public String station_code;
    public String site_code;
    public Time begin_time;
}
