// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.sc.seis.sod.model.station;

import edu.sc.seis.sod.model.common.UnitImpl;

//
// IDL:iris.edu/Fissures/IfNetwork/Stage:1.0
//
/***/

final public class Stage implements org.omg.CORBA.portable.IDLEntity
{
    public
    Stage()
    {
    }

    public
    Stage(TransferType type,
          UnitImpl input_units,
          UnitImpl output_units,
          Normalization[] the_normalization,
          Gain the_gain,
          Decimation[] the_decimation,
          Filter[] filters)
    {
        this.type = type;
        this.input_units = input_units;
        this.output_units = output_units;
        this.the_normalization = the_normalization;
        this.the_gain = the_gain;
        this.the_decimation = the_decimation;
        this.filters = filters;
    }

    public TransferType type;
    public UnitImpl input_units;
    public UnitImpl output_units;
    public Normalization[] the_normalization;
    public Gain the_gain;
    public Decimation[] the_decimation;
    public Filter[] filters;
}
