// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.sc.seis.sod.model.station;

import edu.sc.seis.sod.model.common.QuantityImpl;
import edu.sc.seis.sod.model.common.TimeRange;

//
// IDL:iris.edu/Fissures/IfNetwork/TimeCorrection:1.0
//
/***/

public class TimeCorrection
{
    //
    // IDL:iris.edu/Fissures/IfNetwork/TimeCorrection/effective_time:1.0
    //
    /***/

    public TimeRange effective_time;

    //
    // IDL:iris.edu/Fissures/IfNetwork/TimeCorrection/begin_offset:1.0
    //
    /***/

    public QuantityImpl begin_offset;

    //
    // IDL:iris.edu/Fissures/IfNetwork/TimeCorrection/end_offset:1.0
    //
    /***/

    public QuantityImpl end_offset;

    //
    // IDL:iris.edu/Fissures/IfNetwork/TimeCorrection/who:1.0
    //
    /***/

    public String who;

    protected TimeCorrection() {
    }

    public static TimeCorrection createEmpty() {
    return new TimeCorrection();
    }

    public TimeCorrection(TimeRange effective_time,
                  QuantityImpl begin_offset,
                  QuantityImpl end_offset) {
    this.effective_time = effective_time;
    this.begin_offset = begin_offset;
    this.end_offset = end_offset;
    }
}
