// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.sc.seis.sod.model.station;

//
// IDL:iris.edu/Fissures/IfNetwork/TransferType:1.0
//
/** The allowed transfer types. See blockette 53 field 3 in the SEED 
 *manual.
 **/

final public class TransferType 
{
    private static TransferType [] values_ = new TransferType[4];
    private int value_;

    public final static int _LAPLACE = 0;
    public final static TransferType LAPLACE = new TransferType(_LAPLACE);
    public final static int _ANALOG = 1;
    public final static TransferType ANALOG = new TransferType(_ANALOG);
    public final static int _COMPOSITE = 2;
    public final static TransferType COMPOSITE = new TransferType(_COMPOSITE);
    public final static int _DIGITAL = 3;
    public final static TransferType DIGITAL = new TransferType(_DIGITAL);

    protected
    TransferType(int value)
    {
        values_[value] = this;
        value_ = value;
    }

    public int
    value()
    {
        return value_;
    }

    public static TransferType
    from_int(int value)
    {
        return values_[value];
    }
}
